### ISSUE TITLE
error [-1202] - Wallet not triggering POST request

### ISSUE THREAD

**Issue by escleonh** [kosmigramma/appleshouter#3]
Is there a way to bypass this error? I am able to add the pass but the wallet does not trigger the POST request.
 
Task <CBF31704-C70D-4E20-B1C4-E8F1E1D5E6E5>.<1> finished with error [-1202] Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “localhost” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7fc9db80fa00) s: localhost i: Caddy Local Authority - ECC Intermediate>",
    "<cert(0x7fc9db83e400) s: Caddy Local Authority - ECC Intermediate i: Caddy Local Authority - 2021 ECC Root>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://localhost/webhooks/wallet/ .....

**Comment by hauxir** [comment]
you need to assign an actual domain to your server. What does your Caddyfile look like?

**Comment by escleonh** [comment]
I had this:
localhost {
    reverse_proxy * 127.0.0.1:5000
}
But it is now working after assigning a domain and getting an SSL certificate.
